<?php require __DIR__ . '/layout.php'; admin_layout_start('认证记录', 'record'); ?>
<div class="card"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16px;flex-wrap:wrap;gap:12px">
<select id="statusFilter" onchange="load(1)" style="padding:6px 10px;border:1px solid #E2E8F0;border-radius:6px;font-size:13px"><option value="">全部状态</option><option value="success">通过</option><option value="failed">失败</option><option value="auditing">审核中</option></select>
<a href="/api/export/csv" class="el-button el-button--default el-button--small" style="text-decoration:none">导出CSV</a>
</div>
<div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:13px"><thead><tr style="background:#F1F5F9"><th style="padding:10px 14px;text-align:left;font-weight:600;color:#6B7280;font-size:12px">记录编号</th><th style="padding:10px 14px;text-align:left;font-weight:600;color:#6B7280;font-size:12px">用户ID</th><th style="padding:10px 14px;text-align:left;font-weight:600;color:#6B7280;font-size:12px">状态</th><th style="padding:10px 14px;text-align:left;font-weight:600;color:#6B7280;font-size:12px">活体分数</th><th style="padding:10px 14px;text-align:left;font-weight:600;color:#6B7280;font-size:12px">接口</th><th style="padding:10px 14px;text-align:left;font-weight:600;color:#6B7280;font-size:12px">时间</th><th style="padding:10px 14px;text-align:left;font-weight:600;color:#6B7280;font-size:12px">IP</th></tr></thead><tbody id="tbody"><tr><td colspan="7" style="text-align:center;padding:30px;color:#9CA3AF">加载中...</td></tr></tbody></table></div>
<div id="pager" style="display:flex;align-items:center;justify-content:center;gap:12px;margin-top:20px;font-size:13px"></div>
</div>
<script>
var page=1,statusMap={success:'<span style="display:inline-block;padding:2px 10px;border-radius:99px;font-size:11px;font-weight:500;background:#D1FAE5;color:#10B981">通过</span>',failed:'<span style="display:inline-block;padding:2px 10px;border-radius:99px;font-size:11px;font-weight:500;background:#FEE2E2;color:#EF4444">失败</span>',auditing:'<span style="display:inline-block;padding:2px 10px;border-radius:99px;font-size:11px;font-weight:500;background:#FEF3C7;color:#F59E0B">审核中</span>',pending:'<span style="display:inline-block;padding:2px 10px;border-radius:99px;font-size:11px;font-weight:500;background:#DBEAFE;color:#3B82F6">待处理</span>',processing:'<span style="display:inline-block;padding:2px 10px;border-radius:99px;font-size:11px;font-weight:500;background:#DBEAFE;color:#3B82F6">处理中</span>'};
async function load(p){page=p||1;var status=document.getElementById('statusFilter').value;try{var r=await axios.post('/api/admin/records',{page:page});if(r.data.code===200){var list=r.data.data.list,total=r.data.data.total,limit=20,h='';if(list.length===0)h='<tr><td colspan="7" style="text-align:center;padding:30px;color:#9CA3AF">暂无记录</td></tr>';else list.forEach(function(r){h+='<tr style="border-bottom:1px solid #E2E8F0"><td style="padding:10px 14px;font-family:monospace;font-size:11px">'+(r.record_no||'').substring(0,16)+'...</td><td style="padding:10px 14px">'+r.user_id+'</td><td style="padding:10px 14px">'+(statusMap[r.status]||r.status)+'</td><td style="padding:10px 14px">'+(r.liveness_score||'-')+'</td><td style="padding:10px 14px">'+(r.driver_code||'-')+'</td><td style="padding:10px 14px;font-size:12px">'+(r.certify_time||r.create_time)+'</td><td style="padding:10px 14px;font-size:12px">'+r.ip_address+'</td></tr>'});document.getElementById('tbody').innerHTML=h;var ph='';if(page>1)ph+='<a href="javascript:load('+(page-1)+')" style="padding:6px 12px;border:1px solid #E2E8F0;border-radius:6px;text-decoration:none;color:#6B7280;font-size:12px">上一页</a>';ph+='<span style="color:#6B7280">第 '+page+' 页 / 共 '+Math.ceil(total/limit)+' 页 ('+total+' 条)</span>';if(page*limit<total)ph+='<a href="javascript:load('+(page+1)+')" style="padding:6px 12px;border:1px solid #E2E8F0;border-radius:6px;text-decoration:none;color:#6B7280;font-size:12px">下一页</a>';document.getElementById('pager').innerHTML=ph;}}catch(e){}}
load(1);
</script>
<?php admin_layout_end(); ?>